spring.application.name=secureFort

#spring.security.user.name=user
#spring.security.user.password=admin
#
#
#spring.security.user.name=admin
#spring.security.user.password=secret
#spring.security.user.roles=ADMIN


# H2 database
spring.datasource.url=jdbc:h2:mem:fortdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Create tables automatically
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# H2 console - development only
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.csrf=TRACE
